services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - sentry-web
    environment:
      - DOCKER=True
      - DJANGO_SETTINGS_MODULE=core.settings

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: interview_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  sentry-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - sentry-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  sentry-web:
    image: sentry:9.1.2
    depends_on:
      - sentry-db
      - redis
    environment:
      SENTRY_SECRET_KEY: 'hjfhejrbrewbatatahajrerurdddksat'
      SENTRY_POSTGRES_HOST: sentry-db
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_DB_NAME: sentry
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379
    ports:
      - "9000:9000"
    restart: unless-stopped

  sentry-worker:
    image: sentry:9.1.2
    command: run worker
    depends_on:
      - sentry-db
      - redis
    environment:
      SENTRY_SECRET_KEY: 'hjfhejrbrewbatatahajrerurdddksat'
      SENTRY_POSTGRES_HOST: sentry-db
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_DB_NAME: sentry
      SENTRY_REDIS_HOST: redis

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025" # Веб-интерфейс
      - "1025:1025" # SMTP порт
    restart: always

  celery-worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    env_file:           
      - .env
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - IS_DOCKER=True 

  celery-beat:
    build: .
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:           
      - .env
    depends_on:
      - db      
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - IS_DOCKER=True     
      - POSTGRES_DB=interview_db  
      - POSTGRES_USER=postgres        
      - POSTGRES_PASSWORD=postgres   
      - POSTGRES_HOST=db 
    restart: on-failure:3   

volumes:
  postgres_data:
  sentry-db-data:

