# Generated by Django 5.0.4 on 2026-01-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_historicalvacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'На рассмотрении'), ('reviewed', 'Рассмотрена'), ('interview_scheduled', 'Собеседование назначено'), ('accepted', 'Принята'), ('rejected', 'Отклонёна')], default='submitted', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalvacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('closed', 'Закрыта')], default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('closed', 'Закрыта')], default='published', max_length=20, verbose_name='Статус'),
        ),
    ]
