# Generated by Django 5.0.4 on 2026-06-18 20:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='contact_email',
            field=models.EmailField(default='user@example.com', max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес')], verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='historicalvacancy',
            name='contact_email',
            field=models.EmailField(default='hr@company.com', max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес')], verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='historicalvacancy',
            name='contact_phone',
            field=models.CharField(default='+70000000000', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон для связи'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contact_email',
            field=models.EmailField(default='hr@company.com', max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес')], verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contact_phone',
            field=models.CharField(default='+70000000000', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.UniqueConstraint(fields=('title', 'description', 'company'), name='unique_vacancy_per_company'),
        ),
    ]
