# Generated by Django 5.0.4 on 2026-06-21 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_candidateprofile_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Желаемая должность')),
                ('salary_expected', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ожидаемая зарплата')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('education', models.TextField(verbose_name='Образование')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, to='main.skill', verbose_name='Навыки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-updated_at'],
            },
        ),
    ]
